### ISSUE TITLE
Release 1.0 Gem

### ISSUE THREAD

**Issue by bewatts** [bkroeker/temporal_tables#12]
It looks like we tagged v1.0 a week ago (exciting!) - are there are blockers to releasing it to rubygems?  Do you need any support here @bkroeker ? 

Unfortunately, we have engines / gemspecs that are consuming temporal tables, which cannot consume git urls, so our team needs a released gem.

**Comment by bkroeker** [comment]
Hmm, I had run the command to release it on rubygems, but apparently it didn't work.  I'll need to investigate.

**Comment by bkroeker** [comment]
Aha, apparently the command failed because rubygems requires MFA these days and I missed the error message.  Should be good to go now.
