### ISSUE TITLE
Bug with options in ruby 3

### ISSUE THREAD

**Issue by bewatts** [bkroeker/temporal_tables#13]
I'm trying to do our migration to ruby 3, and running into bugs running my migrations locally - I believe temporal_tables is at cause here.

For a migration that looks like this: 

```
add_column :table, :column, :boolean, default: false, null: false
```

Getting this backtrace:
```
[4] pry(#<AddIsLockedToApplications>)> e.backtrace
=> ["/Users/ben.watts/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql/schema_statements.rb:396:in `add_column'",
 "/Users/ben.watts/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/temporal_tables-1.0.1/lib/temporal_tables/temporal_adapter.rb:86:in `add_column'",
 ```
 
 I believe line 86 of temporal_adapater needs to be
 `super temporal_name(table_name), column_name, type, **options`
 instead of
`super temporal_name(table_name), column_name, type, options`

I also suspect there are other cases of needing to switch to using the `**` operator.

Related description of change in kwargs: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

**Comment by bkroeker** [comment]
This is hopefully all fixed in 1.0.2.  Please let me know if you run into any more issues.
