### ISSUE TITLE
Index name length

### ISSUE THREAD

**Issue by eraffel-MDSol** [bkroeker/temporal_tables#18]
I'm wondering why it's important that the length of the index name not be different on the history table than the original table. I ask because the logic for generating the name assumes that all indexes start with `index` or end with `_ix(\d+)`. This isn't the case for me, and the result is that `temporal_index_name` spits out the same output as the input for some of my indexes, resulting in a duplicate error when it tries to create the index. 

As a workaround, I can rename my indexes, but I'm trying to understand this constraint, rather than just appending `_h` to the index name.

**Comment by bkroeker** [comment]
@eraffel-MDSol Given that database systems impose limits on the length of index names, I didn't want to run into situations where the index name succeeded on the base table but failed on the history table because it was too long.

**Comment by bkroeker** [comment]
To elaborate, rails can generate very long index names when you start indexing multiple columns together. It's not difficult to run into the name limits on indexes.

I'm open to ideas for solutions to your issue. Maybe add an optional config value that accepts a lambda for generating index names?
