### ISSUE TITLE
PK of type UUID 

### ISSUE THREAD

**Issue by eraffel-MDSol** [bkroeker/temporal_tables#19]
The library seems to assume an Id of type `integer`. When adding temporal tables to an existing table, if the PK is of type `:uuid`, this causes problems. I can workaround this by passing `id: :uuid` to the `add_temporal_table` call, but wanted to bring it to your attention, since AR supports uuid PKs since (I think) Rails 6

**Comment by bkroeker** [comment]
Passing `id: :uuid` to the call is an easy solution and I think it was added for exactly this purpose.  Doing better introspection on the existing `id` column does sound like a good future improvement.  Thanks for flagging it.
